servicePreferences:
  commitPreferences:
    includeDateInCommitMessage: true
    composeMessageBasedOnChanges: false
    defaultCommitMessage: "Programmatic commit from Haskell code"
    argsForCommitAction: []
  pushPreferences:
    pushToRemoteAfterCommit: true
    argsForPushAction: []
  addPreferences:
    addAllBeforeCommitting: true
    argsForAddAction: []