managedObjects:
  - location: /home/joe/Development/Repositories/git-autosync
    commitPreferences:
      includeDateInCommitMessage: true
      defaultCommitMessage: "Programmatic commit from Haskell code, so this project commits and pushes itself"
      argsForCommitAction: []
    pushPreferences:
      pushToRemoteAfterCommit: true
      argsForPushAction: []
    addPreferences:
      addAllBeforeCommitting: true
      argsForAddAction: []