servicePreferences:
  commitPreferences:
    includeDateInCommitMessage: true
    composeMessageBasedOnChanges: false
    defaultCommitMessage: ""
    argsForCommitAction: []
  pushPreferences:
    pushToRemoteAfterCommit: true
    argsForPushAction: []
  addPreferences:
    addAllBeforeCommitting: true
    argsForAddAction: []