preferences:
  commitMessage:
    includeDate: false
    messageBasedOnChanges: false
    defaultMessage: ""
    extraArgs: []
  push:
    enable: true
    extraArgs: []
  add:
    addAllPreCommit: true