preferences:
  commitMessage:
    includeDate: false
    messageBasedOnChanges: false
    defaultMessage: ""
    argsForCommitCommand: []
  push:
    enable: true
    argsForPushCommand: []
  add:
    addAllPreCommit: true
    argsForAddCommand: []