name:                git-autosync
version:             0.1.0.0
github:              "githubuser/git-autosync"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/git-autosync#readme>

dependencies:
- base >= 4.7 && < 5
- process >= 1.6.13.2
- time >= 1.9.3
- yaml >= 0.11.8.0
- text >= 1.2.5.0
- bytestring >= 0.10.12.1
- directory >= 1.3.6.2

library:
  source-dirs: src

executables:
  git-autosync-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-autosync

tests:
  git-autosync-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-autosync
